import { spawn, spawnSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import assert from 'node:assert/strict';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ?? 'playwright');
const root = fileURLToPath(new URL('../', import.meta.url));
const tarball = resolve(process.argv[2] ?? join(root, 'artifacts/dsh-riskproof-0.3.0.tgz'));
const home = mkdtempSync(join(tmpdir(), 'riskproof-web-acceptance-'));
const workspace = join(home, 'riskproof-web-acceptance');
mkdirSync(workspace);
const artifacts = join(root, 'artifacts/web'); mkdirSync(artifacts, { recursive: true });
const env = { ...process.env, DSH_HOME: home, RISKPROOF_WEB_WORKSPACE: workspace, RISKPROOF_WEB_BODY_MARKER: join(home, 'unexpected-tool-body.txt') };
const cli = process.env.DSH_BIN ?? 'dsh';
const install = spawnSync(cli, ['plugin', '--profile', 'web', 'add', tarball], { env, encoding: 'utf8', timeout: 60000 });
assert.equal(install.status, 0, install.stderr + install.stdout);
const patch = join(home, 'acceptance.patch.yml');
writeFileSync(patch, `- id: directory-picker\n  disabled: true\n- id: tools\n  config:\n    mode: native\n- id: session-title-llm\n  disabled: true\n- id: agent-default-model\n  config:\n    provider: riskproof-local-test\n    model: deterministic\n- insert:\n    - id: directory-picker-browse-test\n      name: '@deepseek-ai/dsh-host-directory-picker-browse'\n    - id: ui-directory-picker-browse-test\n      name: '@deepseek-ai/dsh-client-ui-directory-picker-browse'\n    - id: riskproof-web-acceptance-fixture\n      name: ${JSON.stringify(join(root, 'scripts/fixtures/web-acceptance.mjs'))}\n`);
const server = spawn(cli, ['--profile', 'web', '--patch', patch, '--no-open', '--port', '0'], { env, stdio: ['ignore', 'pipe', 'pipe'] });
let log = ''; let browser; let page;
const failures = [];
const checks = [];
try {
  const url = await new Promise((done, reject) => {
    const timer = setTimeout(() => reject(new Error('DSH startup timed out')), 20000);
    const consume = data => {
      log += data;
      const match = log.match(/dsh web: (http:\/\/127\.0\.0\.1:\d+\/\?token=\S+)/);
      if (match) { clearTimeout(timer); done(match[1]); }
    };
    server.stdout.on('data', consume); server.stderr.on('data', consume);
    server.on('error', reject); server.on('exit', code => { clearTimeout(timer); reject(new Error(`DSH exited ${code}: ${log}`)); });
  });
  browser = await chromium.launch({ headless: true, ...(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : {}) });
  const unauthenticated = await browser.newContext();
  const unauthorized = await unauthenticated.request.post(new URL('/riskproof/status', url).href, { data: { sessionId: null } });
  assert([401, 403].includes(unauthorized.status()));
  await unauthenticated.close(); checks.push('Dashboard RPC rejects unauthenticated requests');
  page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  page.on('pageerror', error => failures.push(error.message));
  page.on('console', message => { if (message.type() === 'error') failures.push(message.text()); });
  page.setDefaultTimeout(12000);
  await page.goto(url);
  await page.getByRole('button', { name: '继续', exact: true }).click();
  await page.waitForTimeout(300);
  if (await page.getByRole('button', { name: '稍后配置', exact: true }).isVisible()) await page.getByRole('button', { name: '稍后配置', exact: true }).click();
  await page.getByRole('button', { name: '选择工作区', exact: true }).click();
  await page.getByText('riskproof-web-acceptance', { exact: true }).last().click();
  const input = page.locator('[contenteditable="true"]');
  const panel = page.locator('.rp-panel'); const beacon = page.locator('.rp-beacon');
  await beacon.waitFor();
  await page.waitForFunction(() => document.querySelector('.rp-root')?.dataset.state !== 'offline');
  assert(await panel.isHidden(), 'Panel must not open on install');
  await page.screenshot({ path: join(artifacts, '01-live-beacon.png') });
  await beacon.click();
  await page.getByText('等待第一条工具记录', { exact: true }).waitFor();
  await page.screenshot({ path: join(artifacts, '02-empty-overview.png') });
  const close = async () => { await page.getByRole('button', { name: '收起安全概览' }).click(); };
  await close();
  checks.push('Persistent beacon, closed by default, real empty state without demo');
  const command = async suffix => {
    await input.fill(`/riskproof${suffix ? ' ' + suffix : ''}`); await input.press('Escape');
    await page.getByRole('button', { name: '发送消息', exact: true }).click();
    await panel.waitFor();
    return page.locator('.rp-details pre').textContent();
  };
  const completion = '本地验收步骤完成。以上为模拟模型驱动的真实 DSH 工具管线，未调用外部模型。';
  const prompt = async text => {
    const before = await page.getByText(completion, { exact: true }).count();
    await input.fill(text); await page.getByRole('button', { name: '发送消息', exact: true }).click();
    await page.waitForFunction(({ completion, before }) => [...document.querySelectorAll('p')].filter(e => e.textContent === completion).length > before, { completion, before });
  };
  const reading = prompt('网页读取测试');
  await page.waitForFunction(() => document.querySelector('.rp-brand small')?.textContent?.includes('工具执行中'));
  await page.screenshot({ path: join(artifacts, '02b-active-call.png') });
  await reading;
  checks.push('Pending real tool call drives the working state before its execution receipt');
  await page.waitForFunction(() => document.querySelector('.rp-total strong')?.textContent === '1');
  assert(await panel.isHidden(), 'Tool activity must not open panel');
  await prompt('来源命令测试');
  await page.waitForFunction(() => document.querySelector('.rp-count-blocked')?.textContent === '1');
  assert(await panel.isHidden(), 'Blocked calls must not open panel');
  await page.waitForTimeout(1800);
  await page.screenshot({ path: join(artifacts, '03-blocked-beacon.png') });
  await beacon.click();
  assert.match(await page.locator('.rp-flow').innerText(), /riskproof_acceptance_web_fetch[\s\S]*→[\s\S]*riskproof_acceptance_bash/);
  await page.screenshot({ path: join(artifacts, '04-provenance-overview.png') });
  await close();
  assert.match(await command('task read-only'), /read-only/); await close();
  await prompt('只读写入测试');
  await page.waitForFunction(() => document.querySelector('.rp-count-blocked')?.textContent === '2');
  await beacon.click();
  assert.equal(await page.locator('.rp-total strong').textContent(), '3');
  assert.equal(await page.locator('.rp-count-clear').textContent(), '1');
  assert.equal(await page.locator('.rp-risk').count(), 2);
  assert.match(await panel.innerText(), /操作超出本次任务范围/);
  assert(!existsSync(env.RISKPROOF_WEB_BODY_MARKER), 'Denied body executed');
  await page.waitForTimeout(1800);
  await page.screenshot({ path: join(artifacts, '05-live-risk-overview.png') });
  checks.push('Automatic actual-pipeline updates, truthful chart, provenance chain and two denials; no denied bodies executed');
  await page.setViewportSize({ width: 390, height: 844 });
  assert(await panel.evaluate(e => { const r = e.getBoundingClientRect(); return r.left >= 0 && r.top >= 0 && r.right <= innerWidth && e.scrollWidth <= e.clientWidth; }));
  await page.screenshot({ path: join(artifacts, '06-mobile-overview.png') });
  await page.keyboard.press('Escape'); assert(await panel.isHidden());
  await page.setViewportSize({ width: 1440, height: 1000 });
  checks.push('Desktop and 390px overview, keyboard close, no modal or horizontal overflow');
  const demo = await command('demo'); assert.equal((demo.match(/✓/g) ?? []).length, 4);
  assert.equal(await page.locator('.rp-total strong').textContent(), '3');
  assert(!(await page.locator('.rp-details').getAttribute('open')));
  await close();
  for (const mode of ['local-only', 'standard']) { assert((await command('task ' + mode)).includes(mode)); await close(); }
  await prompt('查看报告');
  await page.getByText('1 次工具调用', { exact: true }).last().click();
  await page.getByText('riskproof_report · trace', { exact: true }).click();
  await page.getByText('输出', { exact: true }).last().waitFor();
  assert.equal(await page.locator('.rp-total strong').textContent(), '3');
  checks.push('Commands retained as secondary entry; demo and report tool do not inflate real activity');
  await page.reload(); await beacon.waitFor();
  await page.waitForFunction(() => document.querySelector('.rp-count-blocked')?.textContent === '2');
  assert(await panel.isHidden());
  await page.getByRole('button', { name: /新建会话|新会话/, exact: false }).first().click();
  await page.waitForFunction(() => document.querySelector('.rp-total strong')?.textContent === '0');
  assert.equal(await page.locator('.rp-risk').count(), 0);
  checks.push('Page reload restores live-server counts; new session never displays previous risks');
  await page.route('**/riskproof/**', async route => {
    const body = route.request().postDataJSON();
    await route.fulfill({ contentType: 'application/json', body: JSON.stringify({ type: 'server-response', rpcId: body.rpcId, result: { ok: false, error: { code: 'unavailable', message: 'test outage', details: {} } } }) });
  });
  await page.waitForFunction(() => document.querySelector('.rp-root')?.dataset.state === 'offline');
  assert(await page.locator('.rp-data').isHidden());
  await page.unroute('**/riskproof/**');
  await page.waitForFunction(() => document.querySelector('.rp-root')?.dataset.state === 'ready');
  checks.push('RPC failure removes stale chart; automatic recovery returns current-session state');
  assert.equal(await page.locator('.rp-root').count(), 1);
  assert.equal(await page.locator('dialog.riskproof-report-dialog').count(), 0);
  assert.deepEqual(failures, []);
  checks.push('No browser errors, duplicate widgets or legacy modal');
  const evidence = { testedAt: new Date().toISOString(), dsh: spawnSync(cli, ['--version'], { encoding: 'utf8' }).stdout.trim(), browser: browser.version(), sha256: createHash('sha256').update(readFileSync(tarball)).digest('hex'), tarball, home, checks, fixtures: 'Local deterministic model adapter + synthetic tool bodies, real DSH Agent loop, native tools and command UI; no external model requests.' };
  writeFileSync(join(artifacts, 'acceptance.json'), JSON.stringify(evidence, null, 2) + '\n');
  console.log(JSON.stringify(evidence, null, 2));
} catch (error) {
  if (page) { await page.screenshot({ path: join(artifacts, 'failure.png') }); writeFileSync(join(artifacts, 'failure.txt'), await page.locator('body').innerText()); }
  throw error;
} finally {
  writeFileSync(join(artifacts, 'server.log'), log.replace(/\?token=\S+/g, '?token=[REDACTED]'));
  if (browser) await browser.close();
  server.kill('SIGINT');
}
